### ISSUE TITLE
Suggestion including additional information.

### ISSUE THREAD

**Issue by a-t-0** [help-14/mechanical-keyboard#17]
Thank you for your awesome work! A very nice and graphic overview. I think it might be improved by removing [papercuts](https://www.youtube.com/watch?v=nuE4v5xKIWc) 0. and 1.. Suggestion 2., 3. and 4. could perhaps increase rate of adoption of opensource keyboards. 

Mainly I would like to see for every keyboard:

0. a single link with: pass these files/this zip to your friend with a 3d printer (suggest a fair compensation like for it, e.g. including printer degradation-costs, cause if people don't know it's less easy).
1. a (single) quicklink that opens a single/multiple websites with pre-filled orders that consist of all the remaining components you need to assemple your keyboard (excluding the 3d printables).
2. Challenge: the cheapest fabricated keyboard starts at $160, which is steep. I miss an overview of "this is the cheapest foldable" if you self-assemble (inc. 3d print fee).

3. Additionally, the differences between "mechanical keyboard, cherry keys etc" is a bit intimidating, so an embedded youtube with this is the difference, showing a person typing the selected key type, would be clarifying.
4. To finish it all, embedded youtube videos of the assemblies with clear distinction between "3d printed by your friend" and "ordered online" and how you bring them together, would be awesome, that way people know what they get into and have clear help.

I think these changes could improve the rate of adoption of opensource hardware based on the following logic: including the suggested information lowers the threshold to build one of the listed opensource keyboards. This might lead to more people building their own opensource keyboards, they get ownership about it, which (might) translate{s} into enthusiasm when they're asked about their keyboard, which in turn might inspire others to get hands-on with open-source hardware.

**Comment by help-14** [comment]
Cool suggestion, but there is some things that trouble me:
- My original idea for this repo is just a list for keyboards that is open source, a simple list in one page that is easy to find and choose. To make a keyboard from a->z, that person should have some idea of what to do (print pcb, buy component, cnc or 3d printed), so they won't need 0, 1. And your opinion on 3 and 4 are tutorial which is not really match "open source keyboard".
- In order to do all these I should make it into a website, which there are few people are already done and making another worth it? 
- Making a website is good, i love it too, but I don't thing the current follower of this repo is big enough to invest the time required. Marketing it is another story :v

**Comment by a-t-0** [comment]
Thank you for your quick and detailed response, I understand your deliberations.
